import { Inter, Salsa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Sidebar";

const salsa = Salsa({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-[100vh] bg-gradient-to-r from-green-200 via-green-400 to-purple-700",
          salsa.className
        )}
      >
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
